appWeb1.2/Controllers/AdministracionController.cs
using appWeb1._2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace appWeb1._2.Controllers
{
    public class AdministracionController : Controller
    {
        private readonly pruebadbContext _context;

        public AdministracionController(pruebadbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string correo , string contrasena)
        {
            var validacion = (from a in _context.administracionEmpresa
                              where a.correo.Equals(correo) && a.contrasena.Equals(contrasena)
                              select a).FirstOrDefault();


            if (validacion != null)
            {
                ViewData["id_perfil"] = validacion.id_perfil;
                ViewData["nombre_empresa"] = validacion.nombre_empresa;
                ViewData["descripcion_empresa"] = validacion.descripcion_empresa;
                ViewData["correo"] = validacion.correo;
                ViewData["mision"] = validacion.mision;
                ViewData["vision"] = validacion.vision;
                ViewData["detalle_contacto"] = validacion.detalle_contacto;
                ViewData["contrasena"] = validacion.contrasena;
                bool mostrarFormulario2 = true;

                // Aquí puedes agregar la lógica para validar el correo y la contraseña
                // y establecer la variable mostrarFormulario2 en true si son válidos

                ViewData["mostrarFormulario2"] = "block";

            }
            //return View("~/Views/Administracion/Index.cshtml");
            var comentariosuser = (from c in _context.seccioncoment
                                   join a in _context.administracionEmpresa on c.id_empresa equals a.id_perfil
                                   select new
                                   {
                                       nombreempresa = a.nombre_empresa,
                                       comentario = c.comentario,
                                       valoracion = c.valoracion,
                                   }


                                 ).ToList();
            ViewData["comentariosuser"] = comentariosuser;

            return View();
        }
        public IActionResult buscarempresausuario(string correo, string contrasena)
        {
            


            return RedirectToAction("Index", new { correo,contrasena });


        }
        [HttpPost]
        public IActionResult ActualizarPerfil(int id_perfil, string nombre_empresa, string descripcion_empresa, string correo, string mision, string vision, string detalle_contacto, string contrasena)
        {
            // Obtener el registro correspondiente de la base de datos basándote en el id
            var administrador = _context.administracionEmpresa.FirstOrDefault(a => a.id_perfil == id_perfil);

            if (administrador != null)
            {
                // Actualizar los datos del administrador con los valores recibidos
                administrador.nombre_empresa = nombre_empresa;
                administrador.descripcion_empresa = descripcion_empresa;
                administrador.mision = mision;
                administrador.vision = vision;
                administrador.detalle_contacto = detalle_contacto;
                administrador.contrasena = contrasena;

                // Guardar los cambios en la base de datos
                _context.SaveChanges();
            }

            // Redireccionar a la página de inicio o a otra página según sea necesario
            return RedirectToAction("Index");
        }
        public IActionResult guardartrabajo(Trabajo nuevotrabajo)
        {
            _context.Add(nuevotrabajo);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult guardarperfiladministracion(administracionEmpresa nuevaempresa)
        {
            _context.Add(nuevaempresa);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

appWeb1.2/Controllers/RecursosController.cs
using Microsoft.AspNetCore.Mvc;

namespace appWeb1._2.Controllers
{
    public class RecursosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

appWeb1.2/Controllers/descripcionController.cs
using appWeb1._2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace appWeb1._2.Controllers
{
    public class descripcionController : Controller
    {
        private readonly pruebadbContext _context;

        public descripcionController(pruebadbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var descripciontrabajo = (from d in _context.descripcionTrabajo
                                      join t in _context.Trabajo on d.id_trabajo equals t.idtrabajo
                                      select new
                                      {
                                          nombre_trabajo = t.titulotrabajo,
                                          requerimientos = d.requisitos,
                                          beneficio = d.beneficios,
                                          responsabilidades = d.responsabilidades,
                                          comentarios = d.comentarios,
                                      }).ToList();
            ViewData["descripcionTrabajo"] = descripciontrabajo;

            var comentariosuser = (from c in _context.seccioncoment
                                   join a in _context.administracionEmpresa on c.id_empresa equals a.id_perfil
                                   select new
                                   {
                                       nombreempresa = a.nombre_empresa,
                                       comentario = c.comentario,
                                       valoracion = c.valoracion,
                                   }


                                  ).ToList();
            ViewData["comentariosuser"] = comentariosuser;


            var comboadmin = (from a in _context.administracionEmpresa
                              select a).ToList();
            ViewData["listadoempresas"] = new SelectList(comboadmin, "id_perfil", "nombre_empresa");

            return View();
        }
        public IActionResult Crearcomentario(seccioncoment nuevocomentario)
        {
            _context.Add(nuevocomentario);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

appWeb1.2/Controllers/usuariosController.cs
using appWeb1._2.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;



namespace appWeb1._2.Controllers
{
    public class usuariosController : Controller
    {
        private readonly pruebadbContext _context;

        public usuariosController(pruebadbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(string usuario, string aplicaTrabajo)
        {
            var nombreperfil = (from m in _context.usuarios
                            select m.nombre).Distinct().ToList();
            ViewData["nombreperfil"] = new SelectList(nombreperfil, "nombre");

            var tipoTrabjo = (from m in _context.Trabajo
                                select m.titulotrabajo).Distinct().ToList();
            ViewData["tipoTrabjo"] = new SelectList(tipoTrabjo, "titulotrabajo");

            var dataPerfilTrabajo = (from c in _context.Trabajo
                                select new
                                {
                                    titulotrabajo = c.titulotrabajo,
                                    nombreempresa = c.nombreempresa,
                                    
                                    trabajo = c.tipotrabajo,
                                    
                                }).ToList();

            ViewData["dataPerfilTrabajo"] = dataPerfilTrabajo;

            var gnero = (from m in _context.usuarios
                              select m.genero).Distinct().ToList();
            ViewData["gnero"] = new SelectList(gnero, "genero");




            return View();




        }
        public IActionResult guardarDatos(usuarios nuevoDato)
        {
            _context.Add(nuevoDato);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

       

    }
}

appWeb1.2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Parcial - </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Parcial_2_2023.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="" asp-action="Index"><img src="~/css/Logo2.jpg" width="75px" height="50px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div>
                    <ul class="navbar-nav flex-grow-1 ml-auto text-right">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="trabajoes" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="descripcion" asp-action="Index">Descripcion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Administracion" asp-action="Index">Administracion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Recursos" asp-action="Index">Recursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="usuarios" asp-action="Index">Usuario</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cerrar" asp-action="Index">Cerrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Registrarse" asp-action="Index">Registrarse</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="footer-container text-white bg-secondary border-top">
        <!-- Contenido del footer -->
        <br>
        <p class="text-center">Derechos Reservados: - Miguel Eduardo Zelaya Alvarado - Cesar Eduardo Silva Colocho - Jefferson Javier Avelar Arriaza - Miguel Alexander Cordova Torres - Josue David Alvarado Martinez</p>
        <div class="form-group row">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-4">
                <p>Inicio</p>
                <p>Descripcion</p>
                <p>Administracion</p>
                <p>Recursos</p>
                <p>Usuario</p>
            </div>

            <div class="col-sm-1">
                <br />
                <br />
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
                </svg>
            </div>

            <div class="col-sm-1">
                <br />
                <br />
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
                </svg>
            </div>

            <div class="col-sm-1">
                <br />
                <br />
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
                    <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592zm3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.729.729 0 0 0-.529.247c-.182.198-.691.677-.691 1.654 0 .977.71 1.916.81 2.049.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232z" />
                </svg>
            </div>
            <div class="col-sm-1">
                <br />
                <br />
                <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                    <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z" />
                </svg>
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>